geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'), 
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),

]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('myadmin/', include('adminapp.urls', namespace='myadmin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('social/', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.products, name='products'),
    path('category/<int:category_pk>/', mainapp.category_items, name='category_items'),
    path('category/<int:category_pk>/<int:page_num>/', mainapp.category_items, name='category_items_pages'),


    path('product/<int:product_pk>/', mainapp.product_page, name='product_page'),

    path('contact/', mainapp.contact, name='contact'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('категория товара', max_length=64)
    description = models.TextField('описание', blank=True)
    is_active = models.BooleanField('активность', default=True)

    class Meta:
        verbose_name = 'категория товаров'
        verbose_name_plural = 'категории товаров'
        ordering = ['name']

    def __str__(self):
        return f'Категория {self.name}'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField('имя', max_length=64)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=64, blank=True)
    price = models.DecimalField('цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField('активность', default=True)

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from mainapp.models import ProductCategory, Product



def get_hot_product():
    products = Product.objects.all()
    return random.choice(products)


def get_same_products(product):
    return Product.objects.filter(
        category=product.category).exclude(pk=product.pk)


def index(request):
    context = {
        'page_title': 'главная',
    }
    return render(request, 'mainapp/index.html', context)


def products(request):
    hot_product = get_hot_product()

    context = {
        'page_title': 'каталог',
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }
    return render(request, 'mainapp/products.html', context)


def category_items(request, category_pk, page_num=1):
    if category_pk == 0:
        products = Product.objects.all()
    else:
        products = Product.objects.filter(category_id=category_pk)

    products_paginator = Paginator(products, 2)
    try:
        products = products_paginator.page(page_num)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)

    context = {
        'page_title': 'каталог',
        'products': products,
        'category_pk': category_pk,
    }
    return render(request, 'mainapp/category_items.html', context)


def product_page(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)

    context = {
        'page_title': 'продукт',
        'product': product,
        'category_pk': product.category_id,
    }
    return render(request, 'mainapp/product_page.html', context)


def contact(request):
    _locations = [
        {
            'city': 'Москва',
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'city': 'Владивосток',
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'city': 'Краснодар',
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
    ]

    context = {
        'page_title': 'контакты',
        'locations': _locations,
    }
    return render(request, 'mainapp/contact.html', context)

geekshop/mainapp/templates/mainapp/includes/inc__catalog_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'main:category_items' 0 %}"
               class="{% if request.resolver_match.kwargs.category_pk == 0 %}active{% endif %}">
                все
            </a>
        </li>
        {% for item in catalog_menu %}
            <li>
                <a href="{% url 'main:category_items' item.pk %}"
                   class="{% if request.resolver_match.kwargs.category_pk == item.pk %}active{% endif %}">
                    {{ item.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

geekshop/mainapp/templates/mainapp/includes/inc__main_menu.html
<div class="header clearfix">
    <a href="{% url 'main:index' %}" class="logo"></a>
    <ul class="menu">
        <li>
            <a href="{% url 'main:index' %}"
               class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                домой
            </a>
        </li>
        <li>
            <a href="{% url 'main:products' %}"
               class="{% if request.resolver_match.url_name == 'products' or request.resolver_match.url_name == 'category_items' %}active{% endif %}">
                продукты
            </a>
        </li>
        <li>
            <a href="{% url 'main:contact' %}"
               class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                контакты
            </a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="" data-toggle="dropdown">
                        {{ user.first_name|default:"пользователь"|title }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'auth:update' %}">
                                профиль
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'orders:index' %}">
                                заказы
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        {% endif %}
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'myadmin:index' %}">
                    админка
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'authapp:logout' %}">
                    выход
                </a>
            {% else %}
                <a href="{% url 'authapp:login' %}">
                    вход
                </a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:index' %}" class="basket">
        <span>{{ user.basket_total_cost|floatformat:0 }} руб ({{ user.basket_total_qty }} шт)</span>
    </a>
</div>