geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # ShopUser
    path('', adminapp.ShopUserList.as_view(), name='index'),
    path('user/create/', adminapp.ShopUserCreateView.as_view(), name='user_create'),
    path('user/update/<int:user_pk>/', adminapp.ShopUserUpdateView.as_view(), name='user_update'),
    path('user/delete/<int:user_pk>/', adminapp.ShopUserDeleteView.as_view(), name='user_delete'),

    # ProductCategory
    path('categories/', adminapp.categories, name='categories'),
    path('category/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/products/', adminapp.category_products, name='category_products'),
    path('product/<int:pk>/', adminapp.ProductDetail.as_view(), name='product_detail'),
    path('category/<int:pk>/product/create/', adminapp.product_create, name='product_create'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'), 
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),

]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('myadmin/', include('adminapp.urls', namespace='myadmin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('social/', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.forms import forms, HiddenInput, ModelForm

from mainapp.models import ProductCategory, Product


class AgeValidationMixin:
    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age and age < 18:
            raise forms.ValidationError('Вы слишком молоды!')
        return age


class AdminShopUserCreateForm(UserCreationForm, AgeValidationMixin):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name',
                  'password1', 'password2', 'email', 'age', 'avatar',
                  'is_staff', 'is_superuser', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''
            if field_name == 'password':
                field.widget = HiddenInput()


class AdminShopUserUpdateForm(UserChangeForm, AgeValidationMixin):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'password',
                  'email', 'age', 'avatar',
                  'is_staff', 'is_superuser', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''
            if field_name == 'password':
                field.widget = HiddenInput()


class AdminProductCategoryUpdateForm(ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class AdminProductUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'category':
                field.widget = HiddenInput()

geekshop/adminapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import AdminShopUserUpdateForm, AdminShopUserCreateForm, AdminProductCategoryUpdateForm, \
    AdminProductUpdateForm
from mainapp.models import ProductCategory, Product


class SuperUserOnlyMixin:
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class SetPageTitleMixin:
    page_title = ''

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['page_title'] = self.page_title
        return context


class ShopUserList(SuperUserOnlyMixin, SetPageTitleMixin, ListView):
    model = get_user_model()
    page_title = 'админка/пользователи'


class ShopUserCreateView(SuperUserOnlyMixin, SetPageTitleMixin, CreateView):
    model = get_user_model()
    form_class = AdminShopUserCreateForm
    success_url = reverse_lazy('myadmin:index')


class ShopUserUpdateView(SuperUserOnlyMixin, SetPageTitleMixin, UpdateView):
    model = get_user_model()
    form_class = AdminShopUserUpdateForm
    success_url = reverse_lazy('myadmin:index')
    pk_url_kwarg = 'user_pk'
    page_title = 'админка/пользователи/редактирование'


class ShopUserDeleteView(SuperUserOnlyMixin, SetPageTitleMixin, DeleteView):
    model = get_user_model()
    success_url = reverse_lazy('myadmin:index')
    pk_url_kwarg = 'user_pk'
    page_title = 'админка/пользователи/удаление'


@user_passes_test(lambda x: x.is_superuser)
def categories(request):
    context = {
        'page_title': 'админка/категории',
        'object_list': ProductCategory.objects.all()
    }
    return render(request, 'adminapp/categories_list.html', context=context)


class ProductCategoryCreateView(SuperUserOnlyMixin, SetPageTitleMixin, CreateView):
    model = ProductCategory
    success_url = reverse_lazy('myadmin:categories')
    form_class = AdminProductCategoryUpdateForm
    page_title = 'категории продуктов/создание'


class ProductCategoryUpdateView(SuperUserOnlyMixin, SetPageTitleMixin, UpdateView):
    model = ProductCategory
    success_url = reverse_lazy('myadmin:categories')
    form_class = AdminProductCategoryUpdateForm
    page_title = 'категории продуктов/редактирование'


@user_passes_test(lambda u: u.is_superuser)
def category_products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    object_list = category.product_set.all()
    context = {
        'page_title': f'категория {category.name}/продукты',
        'category': category,
        'object_list': object_list
    }
    return render(request, 'adminapp/category_products_list.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = AdminProductUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse(
                'myadmin:category_products',
                kwargs={'pk': category.pk}
            ))
    else:
        form = AdminProductUpdateForm(
            initial={
                'category': category,
            }
        )

    context = {
        'page_title': 'продукты/создание',
        'form': form,
        'category': category,
    }
    return render(request, 'adminapp/product_update.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def product_update(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     if request.method == 'POST':
#         form = AdminProductUpdateForm(request.POST, request.FILES, instance=product)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse(
#                 'my_admin:category_products',
#                 kwargs={'pk': product.category.pk}
#             ))
#     else:
#         form = AdminProductUpdateForm(instance=product)
#
#     context = {
#         'title': 'продукты/редактирование',
#         'form': form,
#         'category': product.category,
#     }
#     return render(request, 'adminapp/product_update.html', context)
#
#
#
# @user_passes_test(lambda u: u.is_superuser)
# def product_delete(request, pk):
#     obj = get_object_or_404(Product, pk=pk)
#
#     if request.method == 'POST':
#         obj.is_active = False
#         obj.save()
#         return HttpResponseRedirect(reverse(
#             'my_admin:category_products',
#             kwargs={'pk': obj.category.pk}
#         ))
#
#     context = {
#         'title': 'продукты/удаление',
#         'object': obj,
#     }
#     return render(request, 'adminapp/product_delete.html', context)


class ProductDetail(SuperUserOnlyMixin, DetailView):
    model = Product

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ page_title|capfirst }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc__menu.html' %}
        </div>
    {% endblock %}

    {% block container %}
    {% endblock %}

</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="users_list">
        <a href="{% url 'myadmin:category_create' %}" class="btn btn-primary new_user">
            новая категория
        </a>
        {% for category in object_list %}
            <div class="user_record {% if not category.is_active %}not_active{% endif %}">
                <div class="user_role">
                    <a href="{% url 'myadmin:category_update' category.pk %}" class="btn btn-primary">
                        редактировать
                    </a>
                    <a href="{#% url 'myadmin:user_delete' category.pk %#}" class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="user_name">
                    <p><strong>{{ category.name }}</strong></p>
                </div>
                <div>
                    {{ category.description }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/categories_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="categories_list">
        <a href="{% url 'myadmin:category_create' %}"
           class="btn btn-primary new_category">
            новая категория
        </a>
        {% for object in object_list %}
            <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <a href="{% url 'myadmin:category_products' object.pk %}"
                       class="btn btn-info">
                        товары категории
                    </a>
                    <a href="{% url 'myadmin:category_update' object.pk %}"
                       class="btn btn-success">
                        редактировать
                    </a>
                    <a href="{#% url 'myadmin:category_delete' object.pk %#}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="category_desc">
                    {{ object.description }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_products_list.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="products_list">
        <a class="new_product btn btn-default"
           href={% url 'myadmin:product_create' category.pk %}>новый продукт</a>

        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href={% url 'myadmin:product_detail' pk=object.pk %}>подробнее</a>
                    </button>
                    <button>
                        <a href={#% url 'myadmin:product_update' object.pk %#}>редактировать</a>
                    </button>
                    <button>
                        <a href={#% url 'myadmin:product_delete' object.pk %#}>удалить</a>
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|capfirst }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="users_list">
        <a href="{#% url 'myadmin:user_create' %#}" class="btn btn-primary new_user">
            новый пользователь
        </a>
        {% for shop_user in object_list %}
            <div class="user_record {% if not shop_user.is_active %}not_active{% endif %}">
                <img src="/media/{{ shop_user.avatar|default:"avatars/default.jpg" }}" alt="{{ shop_user.username }}">
                <div class="user_role">
                    {% if shop_user.is_superuser %}администратор{% else %}пользователь{% endif %}
                    <a href="{% url 'myadmin:user_update' shop_user.pk %}" class="btn btn-primary">
                        редактировать
                    </a>
                    <a href="{% url 'myadmin:user_delete' shop_user.pk %}" class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="user_name">
                    <p><strong>{{ shop_user.username }}</strong></p>
                    <p>
                        {% if shop_user.first_name %}
                            <b>{{ shop_user.first_name|title }}</b>
                            {% if shop_user.last_name %}
                                <p>{{ shop_user.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ shop_user.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ shop_user.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ shop_user.last_login }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'myadmin:category_products' category.pk %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ object.username }}
        {% if object.first_name %}
            ({{ object.first_name|title }}
                {% if object.last_name %}
                    {{ object.last_name|title }}
                {% endif %})
        {% endif %}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'myadmin:index' %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'myadmin:index' %}"
           class="btn btn-primary form-control last">
            к списку пользователей
        </a>
    </div>
{% endblock %}