geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'), 
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),

]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:product_pk>/', basketapp.add, name='add'),
    path('remove/<int:basket_pk>/', basketapp.remove, name='remove'),
    path('set/<int:basket_pk>/<int:qty>/', basketapp.set),
    # re_path()
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('myadmin/', include('adminapp.urls', namespace='myadmin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('social/', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.products, name='products'),
    path('category/<int:category_pk>/', mainapp.category_items, name='category_items'),
    path('category/<int:category_pk>/<int:page_num>/', mainapp.category_items, name='category_items_pages'),


    path('product/<int:product_pk>/', mainapp.product_page, name='product_page'),

    path('contact/', mainapp.contact, name='contact'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('категория товара', max_length=64)
    description = models.TextField('описание', blank=True)
    is_active = models.BooleanField('активность', default=True)

    class Meta:
        verbose_name = 'категория товаров'
        verbose_name_plural = 'категории товаров'
        ordering = ['name']

    def __str__(self):
        return f'Категория {self.name}'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField('имя', max_length=64)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=64, blank=True)
    price = models.DecimalField('цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField('активность', default=True)

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from mainapp.models import ProductCategory, Product



def get_hot_product():
    products = Product.objects.all()
    return random.choice(products)


def get_same_products(product):
    return Product.objects.filter(
        category=product.category).exclude(pk=product.pk)


def index(request):
    context = {
        'page_title': 'главная',
    }
    return render(request, 'mainapp/index.html', context)


def products(request):
    hot_product = get_hot_product()

    context = {
        'page_title': 'каталог',
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }
    return render(request, 'mainapp/products.html', context)


def category_items(request, category_pk, page_num=1):
    if category_pk == 0:
        products = Product.objects.all()
    else:
        products = Product.objects.filter(category_id=category_pk)

    products_paginator = Paginator(products, 2)
    try:
        products = products_paginator.page(page_num)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)

    context = {
        'page_title': 'каталог',
        'products': products,
        'category_pk': category_pk,
    }
    return render(request, 'mainapp/category_items.html', context)


def product_page(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)

    context = {
        'page_title': 'продукт',
        'product': product,
        'category_pk': product.category_id,
    }
    return render(request, 'mainapp/product_page.html', context)


def contact(request):
    _locations = [
        {
            'city': 'Москва',
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'city': 'Владивосток',
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'city': 'Краснодар',
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
    ]

    context = {
        'page_title': 'контакты',
        'locations': _locations,
    }
    return render(request, 'mainapp/contact.html', context)

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>{{ page_title|default:"магазин"|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    {% block container %}
    {% endblock %}
    <div class="clr"></div>

</div>

<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2020</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>

</body>
</html>

geekshop/mainapp/templates/mainapp/category_items.html
{% extends 'mainapp/base.html' %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc__catalog_menu.html' %}

        <div class="related">
            <div class="title clearfix">
                <h2>Продукты</h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'main:category_items_pages' category_pk products.previous_page_number %}">
                            <
                        </a>
                    {% endif %}
                    <span class="current">страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                    {% if products.has_next %}
                        <a href="{% url 'main:category_items_pages' category_pk products.next_page_number %}">
                            >
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="related-products clearfix">
                {% for item in products %}
                    <div class="block">
                        <a href="{% url 'main:product_page' item.pk %}">
                            <img src="/media/{{ item.image }}" alt="">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ item.name }}</h4>
                                <p>{{ item.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block container %}
    <div class="hero">
        {% include 'mainapp/includes/inc__main_menu.html' %}
        <h1>наши контакты</h1>
    </div>

    <div class="location">
        {% if locations %}
            {% for item in locations %}
                <div class="location-1">
                    <i class="fa fa-map-marker fa-5x"></i>
                    <h4>{{ item.city }}</h4>
                    <div class="contacts">
                        <h5>Телефон</h5>
                        <p>{{ item.phone }}</p>
                    </div>
                    <div class="contacts">
                        <h5>Email</h5>
                        <p>{{ item.email }}</p>
                    </div>
                    <div class="contacts">
                        <h5>Адрес</h5>
                        <p>{{ item.address }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h3>Данные о локациях загружаются</h3>
        {% endif %}
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
{% endblock %}

{% block container %}
    <div class="slider">
        {% include 'mainapp/includes/inc__main_menu.html' %}
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>

    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            <div class="block">
                <a href="#"><img src="/static/img/product-1.jpg" alt="">
                    <div class="text">
                        <img src="/static/img/icon-hover.png" alt="img">
                        <h4>Отличный стул</h4>
                        <p>Расположитесь комфортно. </p>
                    </div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="/static/img/product-2.jpg" alt="">
                    <div class="text">
                        <img src="/static/img/icon-hover.png" alt="">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product_page.html
{% extends 'mainapp/base.html' %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc__catalog_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>

    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc__catalog_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ hot_product.description }}
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for item in same_products %}
                    <div class="block">
                        <a href="{% url 'main:product_page' item.pk %}">
                            <img src="/media/{{ item.image }}" alt="">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ item.name }}</h4>
                                <p>{{ item.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}